custom: ${file(../../serverless.common.yml):custom}

service:  ${self:custom.appName}-FrontEnd

plugins:
  - serverless-s3-sync

provider:
  name: aws

resources:
  Resources:

    FrontEnd:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.frontEndBucketName}-${self:custom.stage}
        WebsiteConfiguration:
          IndexDocument: index.html
    
    FrontEndPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: FrontEnd
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "FrontEnd"
                    },
                    "/*"
                  ]
                ]

  Outputs:

    URL:
      Value:
        !GetAtt [FrontEnd, WebsiteURL]
      Export:
        Name: ${self:custom.appName}-${self:custom.stage}-FrontEndS3BucketURL